//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplicateOracleDBIntoMSSQL.OracleModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.SALES = new HashSet<SALE>();
        }
    
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public decimal VENDOR_ID { get; set; }
        public decimal MEASURMENT_UNIT_ID { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual MEASURMENT_UNITS MEASURMENT_UNITS { get; set; }
        public virtual VENDOR VENDOR { get; set; }
        public virtual ICollection<SALE> SALES { get; set; }
    }
}
