//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplicateOracleDBIntoMSSQL.OracleModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public decimal ID { get; set; }
        public System.DateTime SOLD_ON { get; set; }
        public decimal SUPERMARKET_ID { get; set; }
        public decimal PRODUCT_ID { get; set; }
        public decimal QUANTITY { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SUPERMARKET SUPERMARKET { get; set; }
    }
}
