//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadDataToMySQL.SupermarketsChain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public decimal Id { get; set; }
        public string Name { get; set; }
        public decimal VendorId { get; set; }
        public decimal MeasurmentUnitId { get; set; }
        public decimal Price { get; set; }
    
        public virtual MeasurmentUnit MeasurmentUnit { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
